Checking ENVs import from GitHUB Actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,10 +31,13 @@ jobs:
             docker compose up -d --build
 
             echo "Waiting for containers to be fully operational..."
-            sleep 10  # Увеличьте время ожидания, если нужно больше времени для старта
+            sleep 10  # Увеличьте время ожидания при необходимости
 
             echo "Checking if Flask application container is running..."
             docker compose ps | grep web || (echo "Flask container failed to start!" && exit 1)
+
+            echo "Checking if DATABASE_URL is accessible inside the web container..."
+            docker compose exec web bash -c 'echo $DATABASE_URL && pg_isready -h db -p 5432 -U postgres' || (echo "Database connection failed!" && exit 1)
 
             echo "Running tests inside the Flask application container..."
             docker compose exec web pytest tests --verbose --disable-warnings || (echo "Tests failed!" && exit 1)
