docker compose bugfix ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,10 +34,10 @@ jobs:
             sleep 10  # Увеличьте время ожидания, если нужно больше времени для старта
 
             echo "Checking if Flask application container is running..."
-            docker-compose ps | grep web || (echo "Flask container failed to start!" && exit 1)
+            docker compose ps | grep web || (echo "Flask container failed to start!" && exit 1)
 
             echo "Running tests inside the Flask application container..."
-            docker-compose exec web pytest tests --verbose --disable-warnings || (echo "Tests failed!" && exit 1)
+            docker compose exec web pytest tests --verbose --disable-warnings || (echo "Tests failed!" && exit 1)
 
             echo "Tests completed successfully!"
           EOF
