New CI/CD pipline for both Flask projects

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Test and Deploy on Raspberry PI New
+name: Test and Deploy on Raspberry PI 3B
 
 on:
   push:
@@ -21,14 +21,30 @@ jobs:
       - name: Deploy and Test on Raspberry Pi
         run: |
           ssh -p 8022 -o StrictHostKeyChecking=no dgornostaev@178.218.58.175 << 'EOF'
+            # Go to the first project directory and pull the code
             cd /home/dgornostaev/flask-rest-api-v1
-
-            echo "Pulling latest changes and building Docker containers with environment variables..."
-            docker compose down
-            docker compose up -d --build
+            git pull origin main
+            
+            # Rebuilding and restarting docker containers with forced re-creation
+            echo "Building and recreating Docker containers with updated code for Flask API..."
+            docker compose -f docker-compose.yml down
+            docker compose -f docker-compose.yml up -d --build --force-recreate
+            
+            # Go to the second project directory and pull the code
+            cd /home/dgornostaev/flask-auth-jwt
+            git pull origin main
+            
+            echo "Building and recreating Docker containers with updated code for Auth API..."
+            docker compose -f docker-compose.yml down
+            docker compose -f docker-compose.yml up -d --build --force-recreate
+            
+            # Waiting for containers to be ready
             echo "Waiting for containers to be fully operational..."
             sleep 10
+
+            # Run tests
             echo "Running tests inside the Flask application container..."
-            docker compose exec web pytest tests --verbose --disable-warnings || (echo "Tests failed!" && exit 1)
-            echo "Flask app deployed on Raspberrypi 3B"
+            docker compose -f docker-compose.yml exec web pytest tests --verbose --disable-warnings || (echo "Tests failed!" && exit 1)
+            
+            echo "Deployment and testing completed on Raspberry Pi 3B."
           EOF
